-- MySQL Script generated by MySQL Workbench
-- Wed Jul 17 13:14:54 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Youtube
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Youtube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Youtube` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `Youtube` ;

-- -----------------------------------------------------
-- Table `Youtube`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Youtube`.`playlist` (
  `id_playlist` INT(6) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `date_creation` TIMESTAMP(2) NULL,
  `status` ENUM("public", "private") NULL,
  `user_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_playlist`),
  INDEX `fk_playlist_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_playlist_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Youtube`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Youtube`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Youtube`.`user` (
  `id_user` INT(6) NULL,
  `mail` VARCHAR(50) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NULL,
  `birth_date` TIMESTAMP(2) NULL,
  `gender` ENUM("male", "female") NULL,
  `country` VARCHAR(45) NULL,
  `post_code` VARCHAR(10) NULL,
  `channel_id` VARCHAR(45) NULL,
  `channel_subscribed` INT(6) UNSIGNED NULL,
  `playlist_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `channel_id_UNIQUE` (`channel_id` ASC) VISIBLE,
  INDEX `fk_user_playlist1_idx` (`playlist_id` ASC) VISIBLE,
  CONSTRAINT `fk_user_playlist1`
    FOREIGN KEY (`playlist_id`)
    REFERENCES `Youtube`.`playlist` (`id_playlist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Youtube`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Youtube`.`tag` (
  `id_tag` INT(6) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tag`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Youtube`.`channel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Youtube`.`channel` (
  `id_channel` INT(6) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `date_creation` TIMESTAMP(2) NULL,
  `user_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_channel`),
  INDEX `fk_channel_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_channel_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Youtube`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Youtube`.`video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Youtube`.`video` (
  `id_video` INT(6) NOT NULL,
  `title` VARCHAR(100) NULL,
  `description` VARCHAR(300) NULL,
  `size` DECIMAL(7,2) NULL,
  `name_file` VARCHAR(45) NULL,
  `length` DECIMAL(7,2) NOT NULL,
  `thumbnail` BLOB NULL,
  `times_played` INT UNSIGNED NULL,
  `number_likes` INT UNSIGNED NULL,
  `number_dislikes` INT UNSIGNED NULL,
  `status` SET("public", "hidden", "private") NOT NULL,
  `date_posted` TIMESTAMP(2) NULL,
  `like_id` INT(6) NULL,
  `user_id` INT(6) NOT NULL,
  `tag_id` INT(6) NOT NULL,
  `channel_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_video`),
  INDEX `fk_video_user_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_video_tag1_idx` (`tag_id` ASC) VISIBLE,
  INDEX `fk_video_channel1_idx` (`channel_id` ASC) VISIBLE,
  CONSTRAINT `fk_video_user`
    FOREIGN KEY (`user_id`)
    REFERENCES `Youtube`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_tag1`
    FOREIGN KEY (`tag_id`)
    REFERENCES `Youtube`.`tag` (`id_tag`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_video_channel1`
    FOREIGN KEY (`channel_id`)
    REFERENCES `Youtube`.`channel` (`id_channel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Youtube`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Youtube`.`comment` (
  `id_comment` INT NOT NULL AUTO_INCREMENT,
  `text` VARCHAR(200) NULL,
  `date_posted` TIMESTAMP(2) NULL,
  `like_id` INT(6) NULL,
  `dislike_id` INT(6) NULL,
  `user_id` INT(6) NOT NULL,
  `video_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_comment`),
  INDEX `fk_comment_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_comment_video1_idx` (`video_id` ASC) VISIBLE,
  CONSTRAINT `fk_comment_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Youtube`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comment_video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `Youtube`.`video` (`id_video`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Youtube`.`like`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Youtube`.`like` (
  `id_like` INT(6) NOT NULL,
  `like_option` ENUM("like", "dislike") NULL,
  `date` TIMESTAMP(2) NULL,
  `video_id` INT(6) NOT NULL,
  `comment_id` INT NOT NULL,
  `user_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_like`),
  INDEX `fk_like_video1_idx` (`video_id` ASC) VISIBLE,
  INDEX `fk_like_comment1_idx` (`comment_id` ASC) VISIBLE,
  INDEX `fk_like_user1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_like_video1`
    FOREIGN KEY (`video_id`)
    REFERENCES `Youtube`.`video` (`id_video`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_like_comment1`
    FOREIGN KEY (`comment_id`)
    REFERENCES `Youtube`.`comment` (`id_comment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_like_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Youtube`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `id_product` INT(6) NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `picture` VARCHAR(30) NULL DEFAULT NULL,
  `price` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`id_product`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`burger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`burger` (
  `product_id` INT(6) NOT NULL,
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `burger_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id_product`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `id_category` INT(6) NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`province` (
  `id_province` INT(6) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_province`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`town`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`town` (
  `id_town` INT(6) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `province_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_town`),
  UNIQUE INDEX `province_id` (`province_id` ASC) VISIBLE,
  INDEX `province_id_2` (`province_id` ASC) VISIBLE,
  CONSTRAINT `town_ibfk_1`
    FOREIGN KEY (`province_id`)
    REFERENCES `mydb`.`province` (`id_province`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shop` (
  `id_shop` INT(6) NOT NULL,
  `address` VARCHAR(50) NOT NULL,
  `post_code` MEDIUMINT(15) NOT NULL,
  `town_id` INT(6) NOT NULL,
  `province_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_shop`),
  INDEX `town_id` (`town_id` ASC) VISIBLE,
  INDEX `province_id` (`province_id` ASC) VISIBLE,
  INDEX `town_id_2` (`town_id` ASC) VISIBLE,
  INDEX `province_id_2` (`province_id` ASC) VISIBLE,
  CONSTRAINT `shop_ibfk_1`
    FOREIGN KEY (`town_id`)
    REFERENCES `mydb`.`town` (`id_town`),
  CONSTRAINT `shop_ibfk_2`
    FOREIGN KEY (`province_id`)
    REFERENCES `mydb`.`province` (`id_province`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `id_order` INT(6) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `order_option` VARCHAR(25) NOT NULL,
  `quantity_products` SMALLINT(4) NOT NULL,
  `product_id` INT(6) NOT NULL,
  `price` DECIMAL(7,2) NOT NULL,
  `shop_id` INT(6) NOT NULL,
  `client_id` INT(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id_order`),
  INDEX `shop_id_2` (`shop_id` ASC) VISIBLE,
  INDEX `client_id` (`client_id` ASC) VISIBLE,
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  INDEX `client_id_2` (`client_id` ASC) VISIBLE,
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`id_client`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `orders_ibfk_2`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mydb`.`shop` (`id_shop`),
  CONSTRAINT `orders_ibfk_3`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id_product`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `id_employee` INT(6) NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_employee`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`delivery` (
  `id_delivery` INT(6) NOT NULL,
  `order_id` INT(6) NOT NULL,
  `employee_id` INT(6) NOT NULL,
  `delivery_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_delivery`),
  INDEX `employee_id` (`employee_id` ASC) VISIBLE,
  INDEX `order_id` (`order_id` ASC) VISIBLE,
  CONSTRAINT `delivery_ibfk_1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`id_employee`),
  CONSTRAINT `delivery_ibfk_2`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`orders` (`id_order`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`drink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`drink` (
  `id_drink` INT(6) NOT NULL,
  `product_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_drink`),
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  INDEX `product_id_2` (`product_id` ASC) VISIBLE,
  CONSTRAINT `drink_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id_product`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`pick_up`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pick_up` (
  `order_id` INT(6) NOT NULL,
  `employee_id` INT(6) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  INDEX `order_id` (`order_id` ASC) VISIBLE,
  INDEX `employee_id` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `pick_up_ibfk_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`orders` (`id_order`),
  CONSTRAINT `pick_up_ibfk_2`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`id_employee`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pizza` (
  `product_id` INT(6) NOT NULL,
  `category_id` INT(6) NOT NULL,
  UNIQUE INDEX `product_id` (`product_id` ASC) VISIBLE,
  UNIQUE INDEX `category_id` (`category_id` ASC) VISIBLE,
  CONSTRAINT `pizza_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id_product`),
  CONSTRAINT `pizza_ibfk_2`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`category` (`id_category`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `id_address` INT(6) NOT NULL,
  `street` VARCHAR(50) NOT NULL,
  `number` SMALLINT(4) NOT NULL,
  `floor` SMALLINT(2) NOT NULL,
  `door` SMALLINT(2) NOT NULL,
  `city` VARCHAR(25) NOT NULL,
  `post_code` INT(7) NOT NULL,
  `country` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_address`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `id_employee` INT(6) NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_employee`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `id_client` INT(6) NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `address` VARCHAR(50) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `mail` VARCHAR(50) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `recommend_by_id` INT(6) NULL DEFAULT NULL,
  `sale_employee_id` INT(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id_client`),
  UNIQUE INDEX `sale_employee_id` (`sale_employee_id` ASC) VISIBLE,
  UNIQUE INDEX `recommend_by_id` (`recommend_by_id` ASC) VISIBLE,
  CONSTRAINT `clients_ibfk_1`
    FOREIGN KEY (`sale_employee_id`)
    REFERENCES `mydb`.`employee` (`id_employee`),
  CONSTRAINT `clients_ibfk_2`
    FOREIGN KEY (`recommend_by_id`)
    REFERENCES `mydb`.`client` (`id_client`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`supplier` (
  `id_supplier` INT(6) NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `address_id` INT(6) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `fax` VARCHAR(15) NOT NULL,
  `tin` MEDIUMINT(6) NOT NULL,
  PRIMARY KEY (`id_supplier`),
  UNIQUE INDEX `address_id` (`address_id` ASC) VISIBLE,
  CONSTRAINT `supplier_ibfk_1`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`address` (`id_address`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`glasses` (
  `id_glasses` INT(6) NOT NULL,
  `brand` VARCHAR(25) NOT NULL,
  `glass_graduation` DECIMAL(5,2) NOT NULL,
  `frame_type` SET("floating", "plastic", "metallic") NOT NULL,
  `color_glasses` VARCHAR(15) NOT NULL,
  `glass_color` VARCHAR(25) NOT NULL,
  `price_glasses` DECIMAL(7,2) NOT NULL,
  `supplier_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_glasses`),
  INDEX `supplier_id` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `glasses_ibfk_1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `mydb`.`supplier` (`id_supplier`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`receipt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`receipt` (
  `id_receipt` INT(6) NOT NULL,
  `number` VARCHAR(50) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `client_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_receipt`),
  INDEX `fk_receipt_client1_idx` (`client_id` ASC) VISIBLE,
  CONSTRAINT `fk_receipt_client1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sale` (
  `id_sale` INT(6) NOT NULL,
  `client_id` INT(6) NOT NULL,
  `employee_id` INT(6) NOT NULL,
  `glasses_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_sale`),
  INDEX `client_id` (`client_id` ASC) VISIBLE,
  INDEX `employee_id` (`employee_id` ASC) VISIBLE,
  INDEX `glasses_id` (`glasses_id` ASC) VISIBLE,
  CONSTRAINT `sale_ibfk_1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`id_client`),
  CONSTRAINT `sale_ibfk_2`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`id_employee`),
  CONSTRAINT `sale_ibfk_3`
    FOREIGN KEY (`glasses_id`)
    REFERENCES `mydb`.`glasses` (`id_glasses`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
