-- MySQL Script generated by MySQL Workbench
-- Thu Jul 25 12:31:35 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema optician
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema optician
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optician` ;
USE `optician` ;

-- -----------------------------------------------------
-- Table `optician`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optician`.`address` (
  `id_address` INT(6) NOT NULL,
  `street` VARCHAR(50) NOT NULL,
  `number` SMALLINT(4) NOT NULL,
  `floor` SMALLINT(2) NOT NULL,
  `door` SMALLINT(2) NOT NULL,
  `city` VARCHAR(25) NOT NULL,
  `post_code` VARCHAR(10) NOT NULL,
  `country` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_address`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `optician`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optician`.`employee` (
  `id_employee` INT(6) NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `mail` VARCHAR(50) NOT NULL,
  `address_id` INT(6) NULL,
  PRIMARY KEY (`id_employee`),
  INDEX `address_id_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `address_id`
    FOREIGN KEY (`address_id`)
    REFERENCES `optician`.`address` (`id_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `optician`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optician`.`clients` (
  `id_client` INT(6) NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `mail` VARCHAR(50) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `recommend_by_id` INT(6) NULL DEFAULT NULL,
  `sale_employee_id` INT(6) NULL DEFAULT NULL,
  `receipt_id` INT(6) NULL DEFAULT NULL,
  `address_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_client`),
  UNIQUE INDEX `sale_employee_id` (`sale_employee_id` ASC) VISIBLE,
  UNIQUE INDEX `recommend_by_id` (`recommend_by_id` ASC) VISIBLE,
  INDEX `receipt_id` (`receipt_id` ASC) VISIBLE,
  INDEX `clients_ibfk_4_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `clients_ibfk_1`
    FOREIGN KEY (`sale_employee_id`)
    REFERENCES `optician`.`employee` (`id_employee`),
  CONSTRAINT `clients_ibfk_2`
    FOREIGN KEY (`recommend_by_id`)
    REFERENCES `optician`.`clients` (`id_client`),
  CONSTRAINT `clients_ibfk_3`
    FOREIGN KEY (`receipt_id`)
    REFERENCES `optician`.`receipt` (`id_receipt`),
  CONSTRAINT `clients_ibfk_4`
    FOREIGN KEY (`address_id`)
    REFERENCES `optician`.`address` (`id_address`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `optician`.`receipt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optician`.`receipt` (
  `id_receipt` INT(6) NOT NULL,
  `number` VARCHAR(50) NOT NULL,
  `client_id` INT(6) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_receipt`),
  INDEX `client_id` (`client_id` ASC) VISIBLE,
  CONSTRAINT `receipt_ibfk_1`
    FOREIGN KEY (`client_id`)
    REFERENCES `optician`.`clients` (`id_client`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `optician`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optician`.`supplier` (
  `id_supplier` INT(6) NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `address_id` INT(6) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `fax` VARCHAR(15) NOT NULL,
  `tin` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_supplier`),
  UNIQUE INDEX `address_id` (`address_id` ASC) VISIBLE,
  CONSTRAINT `supplier_ibfk_1`
    FOREIGN KEY (`address_id`)
    REFERENCES `optician`.`address` (`id_address`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `optician`.`glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optician`.`glasses` (
  `id_glasses` INT(6) NOT NULL,
  `brand` VARCHAR(25) NOT NULL,
  `glass_graduation` DECIMAL(5,2) NOT NULL,
  `frame_glasses` ENUM("floating", "plastic", "metallic") NOT NULL,
  `color_glasses` VARCHAR(15) NOT NULL,
  `glass_color` VARCHAR(25) NOT NULL,
  `price_glasses` DECIMAL(7,2) NOT NULL,
  `supplier_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_glasses`),
  INDEX `supplier_id` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `glasses_ibfk_1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `optician`.`supplier` (`id_supplier`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `optician`.`sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optician`.`sale` (
  `id_sale` INT(6) NOT NULL,
  `client_id` INT(6) NOT NULL,
  `employee_id` INT(6) NOT NULL,
  `glasses_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_sale`),
  INDEX `client_id` (`client_id` ASC) VISIBLE,
  INDEX `employee_id` (`employee_id` ASC) VISIBLE,
  INDEX `glasses_id` (`glasses_id` ASC) VISIBLE,
  CONSTRAINT `sale_ibfk_1`
    FOREIGN KEY (`client_id`)
    REFERENCES `optician`.`clients` (`id_client`),
  CONSTRAINT `sale_ibfk_2`
    FOREIGN KEY (`employee_id`)
    REFERENCES `optician`.`employee` (`id_employee`),
  CONSTRAINT `sale_ibfk_3`
    FOREIGN KEY (`glasses_id`)
    REFERENCES `optician`.`glasses` (`id_glasses`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
