-- MySQL Script generated by MySQL Workbench
-- Tue Jul  9 13:22:00 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `id_address` INT(6) NOT NULL,
  `street` VARCHAR(50) NOT NULL,
  `number` SMALLINT(4) NOT NULL,
  `floor` SMALLINT(2) NOT NULL,
  `door` SMALLINT(2) NOT NULL,
  `city` VARCHAR(25) NOT NULL,
  `post_code` INT(7) NOT NULL,
  `country` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_address`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `id_employee` INT(6) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `surname` VARCHAR(50) NOT NULL,
  `tin` VARCHAR(25) NOT NULL,
  `phone_number` VARCHAR(25) NOT NULL,
  `job_position` VARCHAR(25) NOT NULL,
  `shop_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_employee`),
  UNIQUE INDEX `shop_id` (`shop_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`receipt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`receipt` (
  `id_receipt` INT(6) NOT NULL,
  `number` VARCHAR(50) NOT NULL,
  `client_id` INT(6) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_receipt`),
  INDEX `client_id` (`client_id` ASC) VISIBLE,
  CONSTRAINT `receipt_ibfk_1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`clients` (`id_client`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clients` (
  `id_client` INT(6) NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `address` VARCHAR(50) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `mail` VARCHAR(50) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `recommend_by_id` INT(6) NULL DEFAULT NULL,
  `sale_employee_id` INT(6) NULL DEFAULT NULL,
  `receipt_id` INT(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id_client`),
  UNIQUE INDEX `sale_employee_id` (`sale_employee_id` ASC) VISIBLE,
  UNIQUE INDEX `recommend_by_id` (`recommend_by_id` ASC) VISIBLE,
  INDEX `receipt_id` (`receipt_id` ASC) VISIBLE,
  CONSTRAINT `clients_ibfk_1`
    FOREIGN KEY (`sale_employee_id`)
    REFERENCES `mydb`.`employee` (`id_employee`),
  CONSTRAINT `clients_ibfk_2`
    FOREIGN KEY (`recommend_by_id`)
    REFERENCES `mydb`.`clients` (`id_client`),
  CONSTRAINT `clients_ibfk_3`
    FOREIGN KEY (`receipt_id`)
    REFERENCES `mydb`.`receipt` (`id_receipt`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`supplier` (
  `id_supplier` INT(6) NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `address_id` INT(6) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `fax` VARCHAR(15) NOT NULL,
  `tin` MEDIUMINT(6) NOT NULL,
  PRIMARY KEY (`id_supplier`),
  UNIQUE INDEX `address_id` (`address_id` ASC) VISIBLE,
  CONSTRAINT `supplier_ibfk_1`
    FOREIGN KEY (`address_id`)
    REFERENCES `mydb`.`address` (`id_address`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`glasses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`glasses` (
  `id_glasses` INT(6) NOT NULL,
  `brand` VARCHAR(25) NOT NULL,
  `glass_graduation` DECIMAL(5,2) NOT NULL,
  `frame_glasses` VARCHAR(15) NOT NULL,
  `color_glasses` VARCHAR(15) NOT NULL,
  `glass_color` VARCHAR(25) NOT NULL,
  `price_glasses` DECIMAL(7,2) NOT NULL,
  `supplier_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_glasses`),
  INDEX `supplier_id` (`supplier_id` ASC) VISIBLE,
  CONSTRAINT `glasses_ibfk_1`
    FOREIGN KEY (`supplier_id`)
    REFERENCES `mydb`.`supplier` (`id_supplier`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`sale`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`sale` (
  `id_sale` INT(6) NOT NULL,
  `client_id` INT(6) NOT NULL,
  `employee_id` INT(6) NOT NULL,
  `glasses_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_sale`),
  INDEX `client_id` (`client_id` ASC) VISIBLE,
  INDEX `employee_id` (`employee_id` ASC) VISIBLE,
  INDEX `glasses_id` (`glasses_id` ASC) VISIBLE,
  CONSTRAINT `sale_ibfk_1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`clients` (`id_client`),
  CONSTRAINT `sale_ibfk_2`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`id_employee`),
  CONSTRAINT `sale_ibfk_3`
    FOREIGN KEY (`glasses_id`)
    REFERENCES `mydb`.`glasses` (`id_glasses`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `id_product` INT(6) NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `picture` VARCHAR(30) NULL DEFAULT NULL,
  `price` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`id_product`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`burger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`burger` (
  `product_id` INT(6) NOT NULL,
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `burger_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id_product`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `id_category` INT(6) NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`province` (
  `id_province` INT(6) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_province`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`town`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`town` (
  `id_town` INT(6) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `province_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_town`),
  UNIQUE INDEX `province_id` (`province_id` ASC) VISIBLE,
  INDEX `province_id_2` (`province_id` ASC) VISIBLE,
  CONSTRAINT `town_ibfk_1`
    FOREIGN KEY (`province_id`)
    REFERENCES `mydb`.`province` (`id_province`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shop` (
  `id_shop` INT(6) NOT NULL,
  `address` VARCHAR(50) NOT NULL,
  `post_code` MEDIUMINT(15) NOT NULL,
  `town_id` INT(6) NOT NULL,
  `province_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_shop`),
  INDEX `town_id` (`town_id` ASC) VISIBLE,
  INDEX `province_id` (`province_id` ASC) VISIBLE,
  INDEX `town_id_2` (`town_id` ASC) VISIBLE,
  INDEX `province_id_2` (`province_id` ASC) VISIBLE,
  CONSTRAINT `shop_ibfk_1`
    FOREIGN KEY (`town_id`)
    REFERENCES `mydb`.`town` (`id_town`),
  CONSTRAINT `shop_ibfk_2`
    FOREIGN KEY (`province_id`)
    REFERENCES `mydb`.`province` (`id_province`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `id_order` INT(6) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `order_option` VARCHAR(25) NOT NULL,
  `quantity_products` SMALLINT(4) NOT NULL,
  `product_id` INT(6) NOT NULL,
  `price` DECIMAL(7,2) NOT NULL,
  `shop_id` INT(6) NOT NULL,
  `client_id` INT(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id_order`),
  INDEX `shop_id_2` (`shop_id` ASC) VISIBLE,
  INDEX `client_id` (`client_id` ASC) VISIBLE,
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  INDEX `client_id_2` (`client_id` ASC) VISIBLE,
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`client_id`)
    REFERENCES `mydb`.`client` (`id_client`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `orders_ibfk_2`
    FOREIGN KEY (`shop_id`)
    REFERENCES `mydb`.`shop` (`id_shop`),
  CONSTRAINT `orders_ibfk_3`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id_product`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`client` (
  `id_client` INT(6) NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `surname` VARCHAR(25) NOT NULL,
  `address` VARCHAR(50) NOT NULL,
  `post_code` INT(10) NOT NULL,
  `town_id` INT(6) NOT NULL,
  `province_id` INT(6) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `order_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_client`),
  UNIQUE INDEX `town_id` (`town_id` ASC) VISIBLE,
  UNIQUE INDEX `province_id` (`province_id` ASC) VISIBLE,
  INDEX `order_id` (`order_id` ASC) VISIBLE,
  INDEX `order_id_2` (`order_id` ASC) VISIBLE,
  CONSTRAINT `client_ibfk_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`orders` (`id_order`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `client_ibfk_2`
    FOREIGN KEY (`town_id`)
    REFERENCES `mydb`.`town` (`id_town`),
  CONSTRAINT `client_ibfk_3`
    FOREIGN KEY (`province_id`)
    REFERENCES `mydb`.`province` (`id_province`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`employee` (
  `id_employee` INT(6) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `surname` VARCHAR(50) NOT NULL,
  `tin` VARCHAR(25) NOT NULL,
  `phone_number` VARCHAR(25) NOT NULL,
  `job_position` VARCHAR(25) NOT NULL,
  `shop_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_employee`),
  UNIQUE INDEX `shop_id` (`shop_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`delivery` (
  `id_delivery` INT(6) NOT NULL,
  `order_id` INT(6) NOT NULL,
  `employee_id` INT(6) NOT NULL,
  `delivery_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_delivery`),
  INDEX `employee_id` (`employee_id` ASC) VISIBLE,
  INDEX `order_id` (`order_id` ASC) VISIBLE,
  CONSTRAINT `delivery_ibfk_1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`id_employee`),
  CONSTRAINT `delivery_ibfk_2`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`orders` (`id_order`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`drink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`drink` (
  `id_drink` INT(6) NOT NULL,
  `product_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_drink`),
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  INDEX `product_id_2` (`product_id` ASC) VISIBLE,
  CONSTRAINT `drink_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id_product`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`pick_up`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pick_up` (
  `order_id` INT(6) NOT NULL,
  `employee_id` INT(6) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  INDEX `order_id` (`order_id` ASC) VISIBLE,
  INDEX `employee_id` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `pick_up_ibfk_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `mydb`.`orders` (`id_order`),
  CONSTRAINT `pick_up_ibfk_2`
    FOREIGN KEY (`employee_id`)
    REFERENCES `mydb`.`employee` (`id_employee`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `mydb`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pizza` (
  `product_id` INT(6) NOT NULL,
  `category_id` INT(6) NOT NULL,
  UNIQUE INDEX `product_id` (`product_id` ASC) VISIBLE,
  UNIQUE INDEX `category_id` (`category_id` ASC) VISIBLE,
  CONSTRAINT `pizza_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `mydb`.`product` (`id_product`),
  CONSTRAINT `pizza_ibfk_2`
    FOREIGN KEY (`category_id`)
    REFERENCES `mydb`.`category` (`id_category`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
