-- MySQL Script generated by MySQL Workbench
-- Thu Jul 25 12:51:12 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pizza_restaurant
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizza_restaurant
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizza_restaurant` DEFAULT CHARACTER SET utf8 ;
USE `pizza_restaurant` ;

-- -----------------------------------------------------
-- Table `pizza_restaurant`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza_restaurant`.`product` (
  `id_product` INT(6) NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `picture` VARCHAR(30) NULL DEFAULT NULL,
  `price` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`id_product`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizza_restaurant`.`burger`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza_restaurant`.`burger` (
  `product_id` INT(6) NOT NULL,
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  CONSTRAINT `burger_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `pizza_restaurant`.`product` (`id_product`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizza_restaurant`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza_restaurant`.`category` (
  `id_category` INT(6) NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id_category`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizza_restaurant`.`province`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza_restaurant`.`province` (
  `id_province` INT(6) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_province`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizza_restaurant`.`town`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza_restaurant`.`town` (
  `id_town` INT(6) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `province_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_town`),
  UNIQUE INDEX `province_id` (`province_id` ASC) VISIBLE,
  INDEX `province_id_2` (`province_id` ASC) VISIBLE,
  CONSTRAINT `town_ibfk_1`
    FOREIGN KEY (`province_id`)
    REFERENCES `pizza_restaurant`.`province` (`id_province`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizza_restaurant`.`shop`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza_restaurant`.`shop` (
  `id_shop` INT(6) NOT NULL,
  `address` VARCHAR(50) NOT NULL,
  `post_code` VARCHAR(10) NOT NULL,
  `town_id` INT(6) NOT NULL,
  `province_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_shop`),
  INDEX `town_id` (`town_id` ASC) VISIBLE,
  INDEX `province_id` (`province_id` ASC) VISIBLE,
  INDEX `town_id_2` (`town_id` ASC) VISIBLE,
  INDEX `province_id_2` (`province_id` ASC) VISIBLE,
  CONSTRAINT `shop_ibfk_1`
    FOREIGN KEY (`town_id`)
    REFERENCES `pizza_restaurant`.`town` (`id_town`),
  CONSTRAINT `shop_ibfk_2`
    FOREIGN KEY (`province_id`)
    REFERENCES `pizza_restaurant`.`province` (`id_province`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizza_restaurant`.`employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza_restaurant`.`employee` (
  `id_employee` INT(6) NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `surname` VARCHAR(50) NOT NULL,
  `tin` VARCHAR(25) NOT NULL,
  `phone_number` VARCHAR(25) NOT NULL,
  `job_position` ENUM("cooker", "deliverer") NOT NULL,
  PRIMARY KEY (`id_employee`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizza_restaurant`.`delivery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza_restaurant`.`delivery` (
  `id_delivery` INT(6) NOT NULL,
  `employee_id` INT(6) NOT NULL,
  `delivery_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  PRIMARY KEY (`id_delivery`),
  INDEX `employee_id` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `delivery_ibfk_1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `pizza_restaurant`.`employee` (`id_employee`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizza_restaurant`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza_restaurant`.`orders` (
  `id_order` INT(6) NOT NULL,
  `date_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  `order_option` ENUM("delivery", "pick-up") NOT NULL,
  `quantity_products` SMALLINT(4) NOT NULL,
  `product_id` INT(6) NOT NULL,
  `price` DECIMAL(7,2) NOT NULL,
  `shop_id` INT(6) NOT NULL,
  `client_id` INT(6) NULL DEFAULT NULL,
  `delivery_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_order`),
  INDEX `shop_id_2` (`shop_id` ASC) VISIBLE,
  INDEX `client_id` (`client_id` ASC) VISIBLE,
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  INDEX `client_id_2` (`client_id` ASC) VISIBLE,
  INDEX `orders_ibfk_4_idx` (`delivery_id` ASC) VISIBLE,
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`client_id`)
    REFERENCES `pizza_restaurant`.`client` (`id_client`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `orders_ibfk_2`
    FOREIGN KEY (`shop_id`)
    REFERENCES `pizza_restaurant`.`shop` (`id_shop`),
  CONSTRAINT `orders_ibfk_3`
    FOREIGN KEY (`product_id`)
    REFERENCES `pizza_restaurant`.`product` (`id_product`),
  CONSTRAINT `orders_ibfk_4`
    FOREIGN KEY (`delivery_id`)
    REFERENCES `pizza_restaurant`.`delivery` (`id_delivery`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizza_restaurant`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza_restaurant`.`client` (
  `id_client` INT(6) NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `surname` VARCHAR(25) NOT NULL,
  `address` VARCHAR(50) NOT NULL,
  `post_code` VARCHAR(10) NOT NULL,
  `town_id` INT(6) NOT NULL,
  `province_id` INT(6) NOT NULL,
  `phone_number` VARCHAR(15) NOT NULL,
  `order_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_client`),
  UNIQUE INDEX `town_id` (`town_id` ASC) VISIBLE,
  UNIQUE INDEX `province_id` (`province_id` ASC) VISIBLE,
  INDEX `order_id` (`order_id` ASC) VISIBLE,
  INDEX `order_id_2` (`order_id` ASC) VISIBLE,
  CONSTRAINT `client_ibfk_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `pizza_restaurant`.`orders` (`id_order`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `client_ibfk_2`
    FOREIGN KEY (`town_id`)
    REFERENCES `pizza_restaurant`.`town` (`id_town`),
  CONSTRAINT `client_ibfk_3`
    FOREIGN KEY (`province_id`)
    REFERENCES `pizza_restaurant`.`province` (`id_province`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizza_restaurant`.`drink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza_restaurant`.`drink` (
  `id_drink` INT(6) NOT NULL,
  `product_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_drink`),
  INDEX `product_id` (`product_id` ASC) VISIBLE,
  INDEX `product_id_2` (`product_id` ASC) VISIBLE,
  CONSTRAINT `drink_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `pizza_restaurant`.`product` (`id_product`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizza_restaurant`.`pick_up`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza_restaurant`.`pick_up` (
  `order_id` INT(6) NOT NULL,
  `employee_id` INT(6) NOT NULL,
  `date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP() ON UPDATE CURRENT_TIMESTAMP(),
  INDEX `order_id` (`order_id` ASC) VISIBLE,
  INDEX `employee_id` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `pick_up_ibfk_1`
    FOREIGN KEY (`order_id`)
    REFERENCES `pizza_restaurant`.`orders` (`id_order`),
  CONSTRAINT `pick_up_ibfk_2`
    FOREIGN KEY (`employee_id`)
    REFERENCES `pizza_restaurant`.`employee` (`id_employee`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `pizza_restaurant`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza_restaurant`.`pizza` (
  `product_id` INT(6) NOT NULL,
  `category_id` INT(6) NOT NULL,
  UNIQUE INDEX `product_id` (`product_id` ASC) VISIBLE,
  UNIQUE INDEX `category_id` (`category_id` ASC) VISIBLE,
  CONSTRAINT `pizza_ibfk_1`
    FOREIGN KEY (`product_id`)
    REFERENCES `pizza_restaurant`.`product` (`id_product`),
  CONSTRAINT `pizza_ibfk_2`
    FOREIGN KEY (`category_id`)
    REFERENCES `pizza_restaurant`.`category` (`id_category`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
