-- MySQL Script generated by MySQL Workbench
-- Wed Jul 24 13:05:46 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Spotify
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Spotify
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Spotify` DEFAULT CHARACTER SET utf8 ;
USE `Spotify` ;

-- -----------------------------------------------------
-- Table `Spotify`.`paypal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`paypal` (
  `id_paypal` INT(6) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_paypal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`credit_card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`credit_card` (
  `id_credit_card` INT(6) NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(30) NULL,
  `month` VARCHAR(25) NOT NULL,
  `year_expiration` VARCHAR(5) NOT NULL,
  `code_security` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE,
  PRIMARY KEY (`id_credit_card`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`payment` (
  `id_payment` INT(6) NOT NULL,
  `date` TIMESTAMP(2) NULL,
  `order_number` VARCHAR(45) NULL,
  `total_payment` DECIMAL NULL,
  `credit_card_id` INT(6) NOT NULL,
  `paypal_id` INT(6) NOT NULL,
  `credit_card_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_payment`),
  UNIQUE INDEX `order_number_UNIQUE` (`order_number` ASC) VISIBLE,
  INDEX `fk_payment_paypal1_idx` (`paypal_id` ASC) VISIBLE,
  INDEX `fk_payment_credit_card1_idx` (`credit_card_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_paypal1`
    FOREIGN KEY (`paypal_id`)
    REFERENCES `Spotify`.`paypal` (`id_paypal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_credit_card1`
    FOREIGN KEY (`credit_card_id`)
    REFERENCES `Spotify`.`credit_card` (`id_credit_card`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`suscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`suscription` (
  `id_suscription` INT(6) NOT NULL AUTO_INCREMENT,
  `date_initial_suscription` TIMESTAMP(2) NOT NULL,
  `date_renovation` TIMESTAMP(2) NOT NULL,
  `payment_method` ENUM("credit card", "PayPal") NOT NULL,
  `payment_id` INT(6) NOT NULL,
  INDEX `fk_suscription_payment1_idx` (`payment_id` ASC) VISIBLE,
  PRIMARY KEY (`id_suscription`),
  CONSTRAINT `fk_suscription_payment1`
    FOREIGN KEY (`payment_id`)
    REFERENCES `Spotify`.`payment` (`id_payment`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`artist` (
  `id_artist` INT(6) NOT NULL,
  `name` VARCHAR(45) NULL,
  `picture_artist` BLOB(5) NULL,
  `album_id` INT(6) NOT NULL,
  `related_artist_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_artist`),
  INDEX `fk_artist_artist1_idx` (`related_artist_id` ASC) VISIBLE,
  CONSTRAINT `fk_artist_artist1`
    FOREIGN KEY (`related_artist_id`)
    REFERENCES `Spotify`.`artist` (`id_artist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`album` (
  `id_album` INT(6) NOT NULL,
  `title` VARCHAR(45) NULL,
  `year_published` INT(5) NULL,
  `cover` BLOB(5) NULL,
  `artist_id_artist` INT(6) NOT NULL,
  PRIMARY KEY (`id_album`),
  INDEX `fk_album_artist1_idx` (`artist_id_artist` ASC) VISIBLE,
  CONSTRAINT `fk_album_artist1`
    FOREIGN KEY (`artist_id_artist`)
    REFERENCES `Spotify`.`artist` (`id_artist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`song`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`song` (
  `id_song` INT(6) NOT NULL,
  `title` VARCHAR(45) NULL,
  `length` VARCHAR(45) NULL,
  `streams` INT(20) NULL,
  `album_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_song`),
  INDEX `fk_song_album1_idx` (`album_id` ASC) VISIBLE,
  CONSTRAINT `fk_song_album1`
    FOREIGN KEY (`album_id`)
    REFERENCES `Spotify`.`album` (`id_album`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`user` (
  `id_user` INT(6) NOT NULL,
  `mail` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `username` VARCHAR(45) NULL,
  `date_birth` DATE NULL,
  `gender` ENUM("male", "female") NULL,
  `country` VARCHAR(45) NULL,
  `post_code` VARCHAR(15) NULL,
  `type_user` ENUM("free", "premium") NULL,
  `suscription_id` INT(6) NOT NULL,
  `album_id` INT(6) NOT NULL,
  `artist_id` INT(6) NOT NULL,
  `song_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_user`),
  INDEX `album_id_idx` (`album_id` ASC) VISIBLE,
  INDEX `artist_id_idx` (`artist_id` ASC) VISIBLE,
  INDEX `song_id_idx` (`song_id` ASC) VISIBLE,
  INDEX `suscription_id_idx` (`suscription_id` ASC) VISIBLE,
  CONSTRAINT `album_id`
    FOREIGN KEY (`album_id`)
    REFERENCES `Spotify`.`album` (`id_album`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `artist_id`
    FOREIGN KEY (`artist_id`)
    REFERENCES `Spotify`.`artist` (`id_artist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `song_id`
    FOREIGN KEY (`song_id`)
    REFERENCES `Spotify`.`song` (`id_song`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `suscription_id`
    FOREIGN KEY (`suscription_id`)
    REFERENCES `Spotify`.`suscription` (`id_suscription`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Spotify`.`playlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Spotify`.`playlist` (
  `id_playlist` INT(6) NOT NULL,
  `title` VARCHAR(30) NULL,
  `number_songs` INT(5) NULL,
  `date_creation` TIMESTAMP(2) NULL,
  `status` ENUM("deleted", "created") NULL,
  `user_id` INT(6) NOT NULL,
  `song_id` INT(6) NOT NULL,
  PRIMARY KEY (`id_playlist`),
  INDEX `fk_playlist_user1_idx` (`user_id` ASC) VISIBLE,
  INDEX `song_id_idx` (`song_id` ASC) VISIBLE,
  CONSTRAINT `fk_playlist_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `Spotify`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `song_id`
    FOREIGN KEY (`song_id`)
    REFERENCES `Spotify`.`song` (`id_song`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
